- name: Demo on task level variables
  hosts: localhost
  connection: local
  vars:
    course: "Devops"
    time: 2
    trainer: "shiva"
  tasks:
  - vars:
     course: "Devsecops with aiops"
    debug:
     msg: "myself srikanth learning {{course}} with trainer {{trainer}} hours is in{{time}}"

