- name: Demo on variables with common file
  hosts: local
  connection: local
  variablefiles:
  - course.yaml
  tasks:
  - debug:
    msg: "myself srikanth learning {{course}} with trainer {{trainer}} hours is in{{time}}"

