- name: Demo on variables with courese file on same directory
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the information
    debug:
      msg: "myself srikanth learning {{course}} with trainer {{trainer}} hours is in{{time}}"

