- name: Demo on prompt 
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "please enter username"
    private: false  # it will be visible on termainal
  - name: password
    prompt: "please enter password"
    private: true   #it will  be not visible on terminal 
  tasks:
  - name: print the information
    debug:
      msg: "username is: {{ username }} and password is :{{ password }}"
