- name: Demo on prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "please enter username"
    private: false 
  - name: password
    prompt: "please enter password"
    private: true 
  tasks:
  - name: print the information
    debug:
      msg: "username is: {{ username }} and password is :{{ password }}"
