- name: Demo on prompt
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: "please enter username"
    private: false 
  - name: password
    prompt: "please enter password"
    private: true 
  tasks:
  - debug:
      msg: "username is {{username}} and password is {{pasword}}""
