- name: Demo on inventory vars file
  hosts: frontend
  #connection: local
  tasks:
  - name: print information
    debug:
     msg: "myself srikanth learning {{course}} with trainer {{trainer}} hours is in{{time}}" 