- name: demo on variable from Cmd
  hosts: local
  connection: local
  tasks:
  - name: print variable at run time using variable passing in msg {{name}}
    debug:
      msg: "hello {{ name }}"  

      # we runansible-playbook -e name ="srikanth"  09-varsyaml