- name: "print gather facts"
  hosts: frontend
  tasks:
  - name: Printing gathering information
    debug:
      msg: " {{ansible_facts}}" # we can getting like os based on our AMI by this ansible run commands