- name: conditions using ansible fact
  hosts: local
  connection: local
  tasks:
  - name: Redhat check
    when:  ansible_facts.os_family == "RedHat"
    debug:
      msg: " Os family is Redhat ,package manager is dnf"
  - name: ubantu check
    when: ansible_facts.os_family == "Debian"
    debug:
     msg: " Os family is Redhat ,package manager is apt.get"
    
    #ansible_facts is a reserved special variable — Ansible fills it automatically, you just use it.