- name: Demo on shell vs command
  hosts: local
  connection: local
  tasks:
  - name: printing the shell command 
    shell: cat etc/passwd | grep root
    register: user_output
  - debug:
       msg: "{{ user_output }}"