- name: Demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: Checking the roboshop is present or not
    command: id Roboshop
    register: user_output
    ignore_errors: true
  - debug:
     msg: "{{ user_output }}"