- name: Demo on error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Checking the roboshop is present or not
    command: id Roboshop
    register: user_output
    ignore_errors: true
  - debug:
     msg: "{{ user_output }}"

  - name: Creating a User when rc is not 0
    command: useradd roboshop
    when: user_output.rc != 0