- name: Demo on variable
  hosts: localhost
  connection: local
  vars_files:
   - course.yaml
  tasks:
   - debug:
      msg:  "i am learning {{ course }} time is {{ time }} trainer is {{ trainer }}"