- name: Demo on prompt
  hosts: localhost
  connection: local
  vars:
   family: ansible_facts.os_family
  tasks:
   - name: 
     when: family == "RedHat"
     debug:
       msg: "dnf"
   - name: 
     when: family == "ubantu"
     debug:
       msg: "aptget"
