- name: Demo on prompt
  hosts: localhost
  connection: local
  become: yes
  tasks:
   - name: installing multiple packages
     name: "{{ item.name }}"
     state: "{{item.state }}"
     loop:
      - { name: "nginx" , state: "present" }
      - { name: "mysql" , state: "notthere" }
      - { name: "zip" , state: "absent" }
      
    