- name: Demo on register 
  hosts: localhost
  connection: local
  vars:
   a:3
   b:5
  tasks:
   - name: adding numbers and take output by register 
     shell: cat etc/passwd | grep root
     register: user_output  
   - name: Printing user output
     debug:
      msg: "{{ user_output }}"
   